// GENERATED by packages/docs-site/scripts/generate-brand-assets.mjs — do not edit by hand.
// Run `npm run brand -w @tflw/docs-site` to regenerate; `brand-mark.test.mjs` fails if this
// file and that script's GEOMETRY block disagree.
//
// The tflw wordmark (`M233` `H`, `D1286`/`D1287`). Four ink strokes and one rail, and the
// rail is the mark: it crosses t/f/l and turns down into the w's opening stroke, so the accent
// becomes a letterform instead of stopping next to one.
//
// IT PAINTS NOTHING OF ITS OWN. Ink is `currentColor`, so the mark is whatever colour the text
// around it would have been — `--fg` in the landing's hero, `--muted` in the doorbar, and
// `--fg` again on hover, with no rule here knowing any of that. The rail is `var(--accent)`.
// The docs site's amber is its palette and not this page's: the four themes here run cyan, blue,
// violet and blue-on-white, and a fifth hue would be the one element on the page not reading
// tokens (`D1286`).
//
// `height` is the only dimension asked for; the width follows the viewBox's 1.656
// aspect so the mark can never be stretched by a stylesheet that sets one and not the other.

export interface WordmarkProps {
  /** Cap-to-descender box in px. The landing hero is 40, the doorbar 18. */
  readonly height?: number;
  readonly className?: string;
}

export function Wordmark({ height = 40, className }: WordmarkProps) {
  return (
    <svg
      viewBox="0 0 53 32"
      role="img"
      aria-label="tflw"
      height={height}
      width={height * 1.65625}
      className={className}
      fill="none"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <g transform="translate(0.7 0)">
        <g stroke="currentColor" strokeWidth={2.6}>
          <path d="M9,5 L9,21.6 C9,24.6 10.9,25.9 13.3,25.9" />
          <path d="M20,25.9 L20,10.4 C20,7.1 22.1,5.5 25,6" />
          <path d="M30,5 L30,25.9" />
          <path d="M37.6,25.9 L41,15.2 L44.4,25.9 L47.4,13" />
        </g>
        <path d="M4.4,13 L34.6,13 L37.6,25.9" stroke="var(--accent)" strokeWidth={3} />
      </g>
    </svg>
  );
}
