// Render a RunReport into a single self-contained report.html (SPEC §13): a step timeline that
// mirrors the source, req/res panels per API step, failures shown as source line + message.
// Secrets are already redacted in the report data (interpreter, P#30) — this file only escapes.

import type { RequestTrace, ResponseTrace, RunReport, StepResult, TestResult } from '@tflw/runtime';

export function renderReportHtml(report: RunReport): string {
  const title = `testFlow report — ${report.passed}/${report.total} passed`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${STYLE}</style>
</head>
<body>
<header class="run ${report.ok ? 'ok' : 'fail'}">
  <h1>testFlow report</h1>
  <div class="meta">
    <span class="badge ${report.ok ? 'ok' : 'fail'}">${report.ok ? 'PASS' : 'FAIL'}</span>
    <span>${report.passed}/${report.total} passed${report.failed ? ` · ${report.failed} failed` : ''}</span>
    <span>env <code>${esc(report.env)}</code></span>
    <span>seed <code>${report.seed}</code></span>
    <span>now <code>${esc(report.now)}</code></span>
    <span>${report.durationMs} ms</span>
    <span>${esc(report.startedAt)}</span>
  </div>
  ${report.insecure ? '<div class="insecure-warning">⚠ insecure: true — TLS certificate verification was disabled for this run</div>' : ''}
</header>
<main>
${report.tests.map(renderTest).join('\n')}
</main>
<footer>Generated by testFlow · report.html is self-contained and safe to attach to a ticket.</footer>
</body>
</html>
`;
}

function renderTest(test: TestResult): string {
  return `<section class="test ${test.ok ? 'ok' : 'fail'}">
  <h2><span class="dot ${test.ok ? 'ok' : 'fail'}"></span>${esc(test.name)}${test.flaky ? ' <span class="flaky">flaky</span>' : ''} <span class="tms">${test.durationMs} ms</span></h2>
  ${test.error ? `<p class="error">${esc(test.error)}</p>` : ''}
  <ol class="steps">
${test.steps.map(renderStep).join('\n')}
  </ol>
</section>`;
}

function renderStep(step: StepResult): string {
  const panels = step.request ? renderTrace(step.request, step.response) : '';
  return `<li class="step ${step.ok ? 'ok' : 'fail'} kind-${step.kind}">
    <div class="line"><span class="mark">${step.ok ? '✓' : '✗'}</span><code>${esc(step.source)}</code><span class="sms">${step.durationMs} ms</span></div>
    ${step.detail ? `<div class="detail ${step.ok ? '' : 'baddetail'}">${esc(step.detail)}</div>` : ''}
    ${panels}
  </li>`;
}

function renderTrace(req: RequestTrace, res?: ResponseTrace): string {
  const reqBody = req.body ? `<pre class="body">${esc(pretty(req.body))}</pre>` : '';
  const resBlock = res
    ? `<div class="panel res">
        <div class="phead">← ${res.status} ${esc(res.statusText)} · ${res.durationMs} ms</div>
        ${renderHeaders(res.headers)}
        ${res.bodyText ? `<pre class="body">${esc(pretty(res.bodyText))}</pre>` : ''}
      </div>`
    : '';
  return `<div class="trace">
    <div class="panel req">
      <div class="phead">→ ${esc(req.method)} ${esc(req.url)}</div>
      ${renderHeaders(req.headers)}
      ${reqBody}
    </div>
    ${resBlock}
  </div>`;
}

function renderHeaders(headers: Record<string, string>): string {
  const rows = Object.entries(headers);
  if (rows.length === 0) return '';
  return `<table class="headers">${rows.map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table>`;
}

function pretty(text: string): string {
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

const STYLE = `
:root{--bg:#0f1115;--card:#171a21;--fg:#e6e8ec;--mut:#9aa3b2;--ok:#3fb950;--fail:#f85149;--warn:#d29922;--line:#262b36;--code:#0b0d11}
@media (prefers-color-scheme: light){:root{--bg:#f6f7f9;--card:#fff;--fg:#1b1f27;--mut:#5b6472;--ok:#1a7f37;--fail:#cf222e;--warn:#9a6700;--line:#e5e8ec;--code:#f3f4f6}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
header.run{padding:20px 24px;border-bottom:1px solid var(--line)}h1{margin:0 0 8px;font-size:18px}
.meta{display:flex;gap:14px;flex-wrap:wrap;color:var(--mut);align-items:center}
.insecure-warning{margin-top:10px;padding:6px 10px;border-radius:6px;background:var(--warn);color:#1b1f27;font-weight:700}
.badge{padding:2px 10px;border-radius:20px;font-weight:700;color:#fff}.badge.ok{background:var(--ok)}.badge.fail{background:var(--fail)}
code{background:var(--code);padding:1px 5px;border-radius:4px}
main{padding:16px 24px;max-width:1000px}
.test{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--line);border-radius:8px;margin:0 0 16px;padding:12px 16px}
.test.ok{border-left-color:var(--ok)}.test.fail{border-left-color:var(--fail)}
h2{font-size:15px;margin:0 0 8px;display:flex;align-items:center;gap:8px}
.dot{width:9px;height:9px;border-radius:50%;display:inline-block}.dot.ok{background:var(--ok)}.dot.fail{background:var(--fail)}
.flaky{color:var(--warn);border:1px solid var(--warn);border-radius:10px;padding:0 8px;font-size:11px;font-weight:700;text-transform:uppercase}
.tms,.sms{color:var(--mut);font-weight:400;font-size:12px;margin-left:auto}
.error{color:var(--fail);margin:4px 0 10px;white-space:pre-wrap}
ol.steps{list-style:none;margin:0;padding:0}
.step{padding:6px 0;border-top:1px solid var(--line)}
.line{display:flex;align-items:center;gap:8px}.line code{background:transparent;padding:0}
.mark{width:14px;text-align:center;font-weight:700}.step.ok .mark{color:var(--ok)}.step.fail .mark{color:var(--fail)}
.detail{color:var(--mut);margin:2px 0 2px 22px;white-space:pre-wrap}
.detail.baddetail{color:var(--fail)}
.trace{margin:6px 0 4px 22px;display:grid;gap:8px}
.panel{background:var(--code);border:1px solid var(--line);border-radius:6px;overflow:hidden}
.phead{padding:6px 10px;border-bottom:1px solid var(--line);color:var(--mut)}
table.headers{width:100%;border-collapse:collapse;font-size:12px}
table.headers td{padding:3px 10px;border-bottom:1px solid var(--line);vertical-align:top;color:var(--mut)}
table.headers td:first-child{width:180px;color:var(--fg)}
pre.body{margin:0;padding:8px 10px;overflow-x:auto;white-space:pre;font-size:12px}
footer{padding:16px 24px;color:var(--mut);border-top:1px solid var(--line)}
`;
