// Render a RunReport into a single self-contained report.html (SPEC §13): a step timeline that
// mirrors the source, req/res panels per API step, failures shown as source line + message.
// Secrets are already redacted in the report data (interpreter, P#30) — this file only escapes.

import type { AttemptResult, RequestTrace, ResponseTrace, RunReport, StepResult, TestResult } from '@tflw/runtime';

/** A test's slot in the sidebar tree + `<main>`'s panel list — computed once, shared by both. */
interface TestSlot {
  readonly id: string;
  readonly file: string;
  readonly test: TestResult;
}

const UNGROUPED = '(no file)';

export function renderReportHtml(report: RunReport): string {
  const title = `testFlow report — ${report.passed}/${report.total} passed`;
  const slots: TestSlot[] = report.tests.map((test, i) => ({ id: `t${i}`, file: test.file ?? UNGROUPED, test }));

  // Group by file, preserving each file's first-appearance order (already the CLI's per-file run
  // order via `mergeReports`) — a `Map` iterates insertion order, so no separate sort is needed.
  const groups = new Map<string, TestSlot[]>();
  for (const slot of slots) {
    const g = groups.get(slot.file);
    if (g) g.push(slot);
    else groups.set(slot.file, [slot]);
  }

  const firstFailing = slots.find((s) => !s.test.ok);
  const defaultActiveId = (firstFailing ?? slots[0])?.id;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${STYLE}</style>
</head>
<body>
<header class="run ${report.ok ? 'ok' : 'fail'}">
  <h1>testFlow report</h1>
  <div class="meta">
    <span class="badge ${report.ok ? 'ok' : 'fail'}">${report.ok ? 'PASS' : 'FAIL'}</span>
    <span>${report.passed}/${report.total} passed${report.failed ? ` · ${report.failed} failed` : ''}</span>
    <span>env <code>${esc(report.env)}</code></span>
    <span>seed <code>${report.seed}</code></span>
    <span>now <code>${esc(report.now)}</code></span>
    <span>${report.durationMs} ms</span>
    <span>${esc(report.startedAt)}</span>
  </div>
  ${report.insecure ? '<div class="insecure-warning">⚠ insecure: true — TLS certificate verification was disabled for this run</div>' : ''}
</header>
<div class="layout">
${renderSidebar(groups)}
<main>
${slots.map((s) => renderTest(s, s.id === defaultActiveId)).join('\n')}
</main>
</div>
<footer>Generated by testFlow · report.html is self-contained and safe to attach to a ticket.</footer>
<script>${SCRIPT.replace('__DEFAULT_ID__', defaultActiveId ?? '')}</script>
</body>
</html>
`;
}

function renderSidebar(groups: ReadonlyMap<string, TestSlot[]>): string {
  return `<nav class="sidebar">
  <div class="filterbar">
    <input type="search" id="tf-filter" placeholder="filter tests…" autocomplete="off">
    <div class="statusfilter" id="tf-statusfilter">
      <button type="button" data-status="all" class="active">All</button>
      <button type="button" data-status="fail">Failed</button>
      <button type="button" data-status="ok">Passed</button>
    </div>
  </div>
  <div class="tree">
${[...groups.entries()].map(([file, slots]) => renderFileGroup(file, slots)).join('\n')}
  </div>
</nav>`;
}

function renderFileGroup(file: string, slots: readonly TestSlot[]): string {
  const failed = slots.filter((s) => !s.test.ok).length;
  const status = failed > 0 ? 'fail' : 'ok';
  return `    <details class="filegroup ${status}"${failed > 0 ? ' open' : ''} data-file="${esc(file)}">
      <summary><span class="fgdot ${status}"></span><span class="fgname">${esc(file)}</span><span class="fgcount">(${slots.length}${failed > 0 ? `, ${failed} failed` : ''})</span></summary>
      <ul class="testlist">
${slots.map((s) => renderTestLink(s)).join('\n')}
      </ul>
    </details>`;
}

function renderTestLink(slot: TestSlot): string {
  const status = slot.test.ok ? 'ok' : 'fail';
  return `        <li><button type="button" class="testlink ${status}" data-target="${slot.id}">${slot.test.ok ? '✓' : '✗'} ${esc(slot.test.name)}</button></li>`;
}

function renderTest(slot: TestSlot, active: boolean): string {
  const test = slot.test;
  const priorAttempts = test.attempts ? test.attempts.slice(0, -1) : [];
  return `<section class="test ${test.ok ? 'ok' : 'fail'}${active ? ' active' : ''}" id="${slot.id}" data-file="${esc(slot.file)}">
  <h2><span class="dot ${test.ok ? 'ok' : 'fail'}"></span>${esc(test.name)}${test.flaky ? ' <span class="flaky">flaky</span>' : ''} <span class="tms">${test.durationMs} ms</span></h2>
  ${test.error ? `<p class="error">${esc(test.error)}</p>` : ''}
  ${priorAttempts.map(renderAttempt).join('\n')}
  ${test.attempts ? `<p class="attempt-final-label"><span class="attempt-badge ok">attempt ${test.attempts.length} of ${test.attempts.length} — passed</span></p>` : ''}
  <ol class="steps">
${test.steps.map(renderStep).join('\n')}
  </ol>
</section>`;
}

/** A failed prior `retry` attempt, rendered as a collapsed native `<details>` block above the
 * final (kept) attempt's already-visible steps — no JavaScript, so the report stays self-contained
 * (PLAN decision 86, closing SPEC §4.4's known evidence gap). */
function renderAttempt(attempt: AttemptResult): string {
  return `<details class="attempt">
    <summary><span class="attempt-badge fail">attempt ${attempt.attempt} — failed</span>${attempt.error ? ` <span class="attempt-error">${esc(attempt.error)}</span>` : ''}</summary>
    <ol class="steps">
${attempt.steps.map(renderStep).join('\n')}
    </ol>
  </details>`;
}

function renderStep(step: StepResult): string {
  const panels = step.request ? renderTrace(step.request, step.response) : '';
  return `<li class="step ${step.ok ? 'ok' : 'fail'} kind-${step.kind}">
    <div class="line"><span class="mark">${step.ok ? '✓' : '✗'}</span><code>${esc(step.source)}</code><span class="sms">${step.durationMs} ms</span></div>
    ${step.detail ? `<div class="detail ${step.ok ? '' : 'baddetail'}">${esc(step.detail)}</div>` : ''}
    ${panels}
  </li>`;
}

function renderTrace(req: RequestTrace, res?: ResponseTrace): string {
  const reqBody = req.body ? `<pre class="body">${esc(pretty(req.body))}</pre>` : '';
  const resBlock = res
    ? `<div class="panel res">
        <div class="phead">← ${res.status} ${esc(res.statusText)} · ${res.durationMs} ms</div>
        ${renderHeaders(res.headers)}
        ${res.bodyText ? `<pre class="body">${esc(pretty(res.bodyText))}</pre>` : ''}
      </div>`
    : '';
  return `<div class="trace">
    <div class="panel req">
      <div class="phead">→ ${esc(req.method)} ${esc(req.url)}</div>
      ${renderHeaders(req.headers)}
      ${reqBody}
    </div>
    ${resBlock}
  </div>`;
}

function renderHeaders(headers: Record<string, string>): string {
  const rows = Object.entries(headers);
  if (rows.length === 0) return '';
  return `<table class="headers">${rows.map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table>`;
}

function pretty(text: string): string {
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

const STYLE = `
:root{--bg:#0f1115;--card:#171a21;--fg:#e6e8ec;--mut:#9aa3b2;--ok:#3fb950;--fail:#f85149;--warn:#d29922;--line:#262b36;--code:#0b0d11}
@media (prefers-color-scheme: light){:root{--bg:#f6f7f9;--card:#fff;--fg:#1b1f27;--mut:#5b6472;--ok:#1a7f37;--fail:#cf222e;--warn:#9a6700;--line:#e5e8ec;--code:#f3f4f6}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
header.run{padding:20px 24px;border-bottom:1px solid var(--line)}h1{margin:0 0 8px;font-size:18px}
.meta{display:flex;gap:14px;flex-wrap:wrap;color:var(--mut);align-items:center}
.insecure-warning{margin-top:10px;padding:6px 10px;border-radius:6px;background:var(--warn);color:#1b1f27;font-weight:700}
.badge{padding:2px 10px;border-radius:20px;font-weight:700;color:#fff}.badge.ok{background:var(--ok)}.badge.fail{background:var(--fail)}
code{background:var(--code);padding:1px 5px;border-radius:4px}
.layout{display:flex;align-items:flex-start}
.sidebar{flex:0 0 300px;width:300px;max-height:100vh;position:sticky;top:0;overflow-y:auto;border-right:1px solid var(--line);padding:12px}
.filterbar{position:sticky;top:0;background:var(--bg);padding-bottom:8px;margin-bottom:6px}
#tf-filter{width:100%;padding:6px 8px;border-radius:6px;border:1px solid var(--line);background:var(--card);color:var(--fg);font:inherit;margin-bottom:6px}
.statusfilter{display:flex;gap:4px}
.statusfilter button{flex:1;padding:4px 0;border-radius:6px;border:1px solid var(--line);background:var(--card);color:var(--mut);font:inherit;cursor:pointer}
.statusfilter button.active{background:var(--fg);color:var(--bg);border-color:var(--fg)}
details.filegroup{margin:0 0 4px;border-radius:6px}
details.filegroup summary{cursor:pointer;list-style:none;display:flex;gap:6px;align-items:center;padding:5px 6px;border-radius:6px}
details.filegroup summary::-webkit-details-marker{display:none}
details.filegroup summary:hover{background:var(--card)}
.fgdot{width:8px;height:8px;border-radius:50%;flex:0 0 auto}.fgdot.ok{background:var(--ok)}.fgdot.fail{background:var(--fail)}
.fgname{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}
.fgcount{color:var(--mut);font-size:11px}
ul.testlist{list-style:none;margin:0;padding:2px 0 2px 18px}
.testlink{display:block;width:100%;text-align:left;padding:4px 6px;border:none;background:transparent;color:var(--mut);font:inherit;font-size:12px;border-radius:6px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.testlink:hover{background:var(--card)}
.testlink.fail{color:var(--fail)}
.testlink.selected{background:var(--card);color:var(--fg);font-weight:700}
.testlink.hidden-by-filter,details.filegroup.hidden-by-filter{display:none}
main{flex:1;min-width:0;padding:16px 24px;max-width:1000px}
.test{display:none}
.test.active{display:block}
.test{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--line);border-radius:8px;margin:0 0 16px;padding:12px 16px}
.test.ok{border-left-color:var(--ok)}.test.fail{border-left-color:var(--fail)}
h2{font-size:15px;margin:0 0 8px;display:flex;align-items:center;gap:8px}
.dot{width:9px;height:9px;border-radius:50%;display:inline-block}.dot.ok{background:var(--ok)}.dot.fail{background:var(--fail)}
.flaky{color:var(--warn);border:1px solid var(--warn);border-radius:10px;padding:0 8px;font-size:11px;font-weight:700;text-transform:uppercase}
details.attempt{margin:6px 0;border:1px solid var(--line);border-left:3px solid var(--fail);border-radius:6px;background:var(--card)}
details.attempt summary{cursor:pointer;padding:6px 10px;list-style:none;display:flex;gap:8px;align-items:center}
details.attempt summary::-webkit-details-marker{display:none}
details.attempt[open] summary{border-bottom:1px solid var(--line)}
.attempt-badge{padding:1px 8px;border-radius:10px;font-size:11px;font-weight:700;text-transform:uppercase}
.attempt-badge.fail{background:var(--fail);color:#fff}
.attempt-badge.ok{background:var(--ok);color:#fff}
.attempt-error{color:var(--mut);font-size:12px}
.attempt-final-label{margin:6px 0 4px}
details.attempt ol.steps{padding:4px 12px 4px 12px}
.tms,.sms{color:var(--mut);font-weight:400;font-size:12px;margin-left:auto}
.error{color:var(--fail);margin:4px 0 10px;white-space:pre-wrap}
ol.steps{list-style:none;margin:0;padding:0}
.step{padding:6px 0;border-top:1px solid var(--line)}
.line{display:flex;align-items:center;gap:8px}.line code{background:transparent;padding:0}
.mark{width:14px;text-align:center;font-weight:700}.step.ok .mark{color:var(--ok)}.step.fail .mark{color:var(--fail)}
.detail{color:var(--mut);margin:2px 0 2px 22px;white-space:pre-wrap}
.detail.baddetail{color:var(--fail)}
.trace{margin:6px 0 4px 22px;display:grid;gap:8px}
.panel{background:var(--code);border:1px solid var(--line);border-radius:6px;overflow:hidden}
.phead{padding:6px 10px;border-bottom:1px solid var(--line);color:var(--mut)}
table.headers{width:100%;border-collapse:collapse;font-size:12px}
table.headers td{padding:3px 10px;border-bottom:1px solid var(--line);vertical-align:top;color:var(--mut)}
table.headers td:first-child{width:180px;color:var(--fg)}
pre.body{margin:0;padding:8px 10px;overflow-x:auto;white-space:pre;font-size:12px}
footer{padding:16px 24px;color:var(--mut);border-top:1px solid var(--line)}
@media print{.sidebar{display:none}.test{display:block!important}main{max-width:none}}
`;

/** Tab-switching, filtering, and default-selection — the report's one bit of interactivity. Still
 * fully self-contained (no external requests, opens via file:// the same as before), just no
 * longer JS-free (decision 92: gap-#3/#8's "reuse existing mechanism" pattern doesn't apply here,
 * since there's no existing mechanism for a tab UI — a pure-CSS `:checked` hack couldn't do
 * default-select-first-failure or the filter box). `__DEFAULT_ID__` is substituted with the id of
 * the section that should be active on load (the first failing test, or the first test if the run
 * is all green) before this string is embedded — done as a literal substitution rather than
 * templating the whole script, so the script body itself stays a plain, readable constant. */
const SCRIPT = `
(function(){
  var sidebar = document.querySelector('.sidebar');
  var main = document.querySelector('main');
  if (!sidebar || !main) return;

  function activate(id){
    main.querySelectorAll('.test.active').forEach(function(el){ el.classList.remove('active'); });
    var panel = id && document.getElementById(id);
    if (panel) panel.classList.add('active');
    sidebar.querySelectorAll('.testlink.selected').forEach(function(el){ el.classList.remove('selected'); });
    var link = id && sidebar.querySelector('.testlink[data-target="' + id + '"]');
    if (link) link.classList.add('selected');
  }

  sidebar.querySelectorAll('.testlink').forEach(function(link){
    link.addEventListener('click', function(){ activate(link.getAttribute('data-target')); });
  });

  var statusFilter = 'all';
  function applyFilter(){
    var q = (document.getElementById('tf-filter').value || '').toLowerCase();
    sidebar.querySelectorAll('details.filegroup').forEach(function(group){
      var links = group.querySelectorAll('.testlink');
      var visibleCount = 0;
      links.forEach(function(link){
        var matchesText = link.textContent.toLowerCase().indexOf(q) !== -1;
        var matchesStatus = statusFilter === 'all' || link.classList.contains(statusFilter);
        var show = matchesText && matchesStatus;
        link.parentElement.classList.toggle('hidden-by-filter', !show);
        if (show) visibleCount++;
      });
      group.classList.toggle('hidden-by-filter', visibleCount === 0);
    });
  }
  document.getElementById('tf-filter').addEventListener('input', applyFilter);
  document.querySelectorAll('#tf-statusfilter button').forEach(function(btn){
    btn.addEventListener('click', function(){
      statusFilter = btn.getAttribute('data-status');
      document.querySelectorAll('#tf-statusfilter button').forEach(function(b){ b.classList.remove('active'); });
      btn.classList.add('active');
      applyFilter();
    });
  });

  activate('__DEFAULT_ID__');
})();
`;
