// M32 (PLAN_REPORTS_PERF_SECURITY.md R2/R3/R6) — render a `LoadReport` into `load-report.html`: a
// self-contained (no CDN, no external JS) human-facing view, purpose-built for load-test data
// rather than reusing `report.html`'s per-test layout (R1: "a percentile never masquerades as
// test-shaped data"). Combined view first (the quotable numbers), then one section per scenario
// (R6) — each with its own metrics table, threshold verdicts, and chart set (R3).

import type { BackOffDiagnosis, LoadMetrics, LoadReport, LoadThresholdResult, SelfDiagnosis } from '@tflw/runtime';
import { renderLatencyOverTimeChart, renderThroughputChart, renderErrorRateChart, renderHistogramChart, esc, CHART_STYLE } from './load-charts.js';

export function renderLoadReportHtml(report: LoadReport): string {
  const status = report.inconclusive ? 'inconclusive' : report.ok ? 'ok' : 'fail';
  const statusLabel = report.inconclusive ? 'INCONCLUSIVE' : report.ok ? 'PASS' : 'FAIL';
  const title = `tflw load report — ${statusLabel}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${STYLE}${CHART_STYLE}</style>
</head>
<body>
<header class="run ${status}">
  <h1>tflw load report</h1>
  <div class="meta">
    <span class="badge ${status}">${statusLabel}</span>
    <span>${report.durationMs} ms</span>
    <span>${esc(report.startedAt)}</span>
    <span>seed <code>${report.seed}</code></span>
    <span>now <code>${esc(report.now)}</code></span>
  </div>
  ${report.aborted ? `<div class="aborted-banner">⚠ ${esc(report.abortedMessage ?? 'aborted before its planned duration elapsed')} — every number below reflects only what completed before Ctrl-C.</div>` : ''}
  ${report.inconclusive ? '<div class="inconclusive-banner">⚠ tflw\'s own generator process saturated during this run — see "generator" below. These numbers reflect tflw contending with itself, not the system under test.</div>' : ''}
</header>
<main>
${renderGeneratorSection(report.selfDiagnosis)}
${renderMetricsSection('Combined', report.combined, [])}
${report.scenarios.map((s) => renderMetricsSection(`Scenario "${s.name}"`, s.metrics, s.thresholds, s.workload, s.backOff)).join('\n')}
</main>
<footer>Generated by testFlow · load-report.html is self-contained and safe to attach to a ticket.</footer>
</body>
</html>
`;
}

function renderGeneratorSection(d: SelfDiagnosis): string {
  const stats = `avg event-loop lag ${d.avgEventLoopLagMs.toFixed(1)}ms · max ${d.maxEventLoopLagMs.toFixed(1)}ms · cpu ${d.cpuPercent.toFixed(0)}%`;
  return `<section class="generator ${d.saturated ? 'saturated' : 'healthy'}">
  <h2>Generator</h2>
  <p>${d.saturated ? `⚠ ${esc(stats)} — tflw itself was the bottleneck` : esc(stats)}</p>
</section>`;
}

function renderMetricsSection(heading: string, metrics: LoadMetrics, thresholds: readonly LoadThresholdResult[], workload?: { readonly kind: 'users' | 'rps'; readonly target: number; readonly overMs: number }, backOff?: BackOffDiagnosis): string {
  const d = metrics.durations;
  return `<section class="metrics-block">
  <h2>${esc(heading)}</h2>
  ${workload ? `<p class="workload">${workload.kind === 'users' ? `ramp to ${workload.target} users` : `ramp to ${workload.target} rps`} over ${workload.overMs}ms</p>` : ''}
  <table class="stats">
    <tr><th>iterations</th><td>${metrics.iterations}</td><th>failures</th><td>${metrics.failures}</td><th>error rate</th><td>${(metrics.errorRate * 100).toFixed(2)}%</td></tr>
    <tr><th>min</th><td>${d.min}ms</td><th>avg</th><td>${Math.round(d.avg)}ms</td><th>max</th><td>${d.max}ms</td></tr>
    <tr><th>p50</th><td>${d.p50}ms</td><th>p90</th><td>${d.p90}ms</td><th>p95</th><td>${d.p95}ms</td><th>p99</th><td>${d.p99}ms</td></tr>
  </table>
  ${backOff?.warning ? `<p class="backoff-warning">⚠ your load backed off — an estimated ${(backOff.ratio * 100).toFixed(0)}% of this scenario's available VU time was lost to the target system slowing down; results understate real latency (coordinated omission, D17)</p>` : ''}
  ${renderThresholdsTable(thresholds)}
  <div class="charts">
    ${renderLatencyOverTimeChart(metrics.timeline)}
    ${renderThroughputChart(metrics.timeline)}
    ${renderErrorRateChart(metrics.timeline)}
    ${renderHistogramChart(metrics.histogram)}
  </div>
</section>`;
}

function renderThresholdsTable(thresholds: readonly LoadThresholdResult[]): string {
  if (thresholds.length === 0) return '';
  const rows = thresholds
    .map((t) => {
      const cmp = t.op === 'lessThan' ? '&lt;' : '&gt;';
      const actual = t.label === 'error rate' ? `${(t.actual * 100).toFixed(2)}%` : `${Math.round(t.actual)}ms`;
      const target = t.label === 'error rate' ? `${(t.target * 100).toFixed(2)}%` : `${t.target}ms`;
      return `<tr class="${t.ok ? 'ok' : 'fail'}"><td>${t.ok ? '✓' : '✗'}</td><td>${esc(t.label)} ${cmp} ${esc(target)}</td><td>actual: ${esc(actual)}</td></tr>`;
    })
    .join('');
  return `<table class="thresholds">${rows}</table>`;
}

const STYLE = `
:root{--bg:#0f1115;--card:#171a21;--fg:#e6e8ec;--mut:#9aa3b2;--ok:#3fb950;--fail:#f85149;--warn:#d29922;--info:#58a6ff;--line:#262b36;--code:#0b0d11}
@media (prefers-color-scheme: light){:root{--bg:#f6f7f9;--card:#fff;--fg:#1b1f27;--mut:#5b6472;--ok:#1a7f37;--fail:#cf222e;--warn:#9a6700;--info:#0969da;--line:#e5e8ec;--code:#f3f4f6}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
header.run{padding:20px 24px;border-bottom:1px solid var(--line)}h1{margin:0 0 8px;font-size:18px}
.meta{display:flex;gap:14px;flex-wrap:wrap;color:var(--mut);align-items:center}
code{background:var(--code);padding:1px 5px;border-radius:4px}
.badge{padding:2px 10px;border-radius:20px;font-weight:700;color:#fff}
.badge.ok{background:var(--ok)}.badge.fail{background:var(--fail)}.badge.inconclusive{background:var(--warn);color:#1b1f27}
.aborted-banner,.inconclusive-banner{margin-top:10px;padding:6px 10px;border-radius:6px;background:var(--warn);color:#1b1f27;font-weight:700}
main{padding:16px 24px;max-width:900px}
section{margin-bottom:20px}
h2{font-size:15px;margin:0 0 8px}
.generator{padding:8px 12px;border-radius:8px;border:1px solid var(--line);background:var(--card)}
.generator.saturated p{color:var(--warn);font-weight:700}
.generator p{margin:0;color:var(--mut)}
.workload{color:var(--mut);margin:0 0 8px}
.backoff-warning{margin:0 0 8px;padding:6px 10px;border-radius:6px;background:var(--warn);color:#1b1f27;font-weight:700}
table.stats{border-collapse:collapse;width:100%;margin-bottom:8px}
table.stats th{text-align:left;color:var(--mut);font-weight:400;padding:3px 8px 3px 0}
table.stats td{padding:3px 16px 3px 0}
table.thresholds{border-collapse:collapse;width:100%;margin-bottom:8px}
table.thresholds td{padding:3px 10px 3px 0}
table.thresholds tr.ok td:first-child{color:var(--ok)}
table.thresholds tr.fail td:first-child{color:var(--fail)}
.charts{display:grid;grid-template-columns:1fr 1fr;gap:10px}
@media (max-width:700px){.charts{grid-template-columns:1fr}}
footer{padding:16px 24px;color:var(--mut);border-top:1px solid var(--line)}
`;
