#!/usr/bin/env node
// The repository's ONE citation classifier — the patterns that decide whether a string names an
// identifier out of this project's private design record.
//
// WHY IT IS ITS OWN FILE (`D795`, corrected). `M158c` merged the two classifiers this repository
// used to keep — `doc-blocks.mjs`'s `NOTATION` and this list — and made the docs-site guard import
// the surviving one. The import direction was right and stands; the import *target* was wrong, and
// coverage is what said so. `verify-citations.mjs` is a 380-line gate that pulls in
// `gen-decisions.mjs` behind it, and neither is exercised by the docs-site suite. Importing it
// dragged both into c8's file set — the denominator is `.c8rc.json`'s `src` list PLUS whatever the
// tests happen to load — and global function coverage fell 95.1% -> 93.56% against a 94% floor.
//
// That floor is pinned one point under a real measurement and its own script says *do not lower it
// to make a red run green*, so the fix is the file set rather than the number. Splitting the
// patterns out is `D795`'s stated fallback arriving for a reason `D795` did not predict: it kept
// the fallback at `packages/lang/src/`, and this is better, because a citation classifier is not
// language surface — `D795` says so itself.
//
// The rules are data. Everything that *uses* them — the prose scanner, the package-metadata walk,
// the docs-site page guard — stays where it was.

/**
 * The old spelling. `decision 57`, `decisions 74–83`, `design decision 12`, `Decision 7` — the
 * leading `(?<![\w])` keeps `subdecision 4` out, and the optional `design ` prefix exists because
 * `PLAN_M13_LSP.md` numbers its own sequence that way (`D687`'s ninth namespace).
 *
 * Only the opening number is captured. A phrase carrying several targets (`decisions 93–96, 103`)
 * is one finding, not four: it is one sentence, read once, rewritten once.
 */
export const BARE = /(?<![\w])(?:design\s+)?decisions?\s+(?:no\.\s*)?\d{1,3}[a-z]?/gi;

/**
 * The same spelling with a **letter** where the number goes (`D716`). `PLAN_M13_LSP.md` numbers a
 * pair of LSP decisions `A` and `B`, which is a tenth namespace on top of `D687`'s nine and the one
 * `M152c-01` singled out as *"a sixth numbering nothing in this repository indexes"* — and every
 * matcher in this repository missed it, because `BARE` above is digits-only.
 *
 * A **separate regex, without the `i` flag**, rather than widening `BARE`'s character class. That
 * was measured, not assumed: `decisions?\s+[0-9A-Za-z]+` — the form the scoping proposed — finds 36
 * phrases in tracked markdown and 33 are ordinary English (`decision the`, `decision rather`,
 * `decision was`). Keeping `i` and matching one letter still reads `a decision a human recorded`
 * (`SPEC.md:3058`) as a citation. One **uppercase** letter, case-sensitively, finds three phrases in
 * the whole corpus and all three are real.
 *
 * No exemption ships with it, per `D708`: an exemption that exempts nothing does not get built. Two
 * shapes are foreseeable and neither occurs — `decision I` (the pronoun) and `decision N` (the
 * notation quoted rather than used, which `inCodeSpan` already covers everywhere it appears).
 */
export const BARE_LETTER = /(?<![\w])(?:[Dd]esign\s+)?[Dd]ecisions?\s+(?:no\.\s*)?[A-Z]\b/g;

/**
 * The founding list in its oldest spelling — `#37`, no `P`. Seven survive, all inside entries
 * lifted from `PLAN.md`, and a `decision N` regex does not see them (`D692` counted five; the two
 * it missed are `#35` at `P#41` and `P#49`).
 *
 * The `#n` shape is shared by four namespaces that are not this one, so the preceding word decides.
 * `gap #9` indexes `TFLW-GAPS.md`, which the index's preamble already declares rather than repairs
 * (`D688`); `PR #97` and `PRs #12–#18` are GitHub; `UTS #39` and `OWASP API #1` are external
 * standards. None is a decision citation, and a gate that flagged them would be asking for a
 * rewrite that made each one wrong.
 */
export const BARE_HASH = /(?<![\w)\]#/-])#(\d{1,3})\b/g;

/**
 * The notation as it appears in `package.json`, where every rule above changes meaning (`D715`).
 *
 * Two differences drive this, and both run the opposite way to the prose corpus:
 *
 * 1. **Naming the record is the defect, not the repair.** In tracked prose, `PLAN_ENTERPRISE.md
 *    decision 17` is as resolvable as that sequence gets, so `NAMES_RECORD` exempts it. Shipped
 *    metadata has no such reader: every `PLAN*.md` in this repository is gitignored and none of
 *    them has ever left it, so the filename resolves to nothing at all for the person reading
 *    `npm view tflw`. Here the record name is a **positive** signal.
 * 2. **There is no line, so there is a path.** A finding names
 *    `.contributes.configuration.properties.tflw.env.description`, because a line number in a file
 *    that is regenerated by tooling points at nothing a reader can act on.
 *
 * `webV2-1` (`testFlow-tests/webV2/admin`) is **knowingly** outside all of this — `D718`. It is a
 * record-local sequence with no record name in front of it, and the only rule broad enough to catch
 * it would flag every hyphenated token in every description. It is repaired by hand; the gate is
 * documented as unable to see its shape, so the next one gets through knowingly rather than
 * silently. A wordlist of record-local prefixes is refused for `D659`'s reason: this repository's
 * guards do not maintain wordlists, and a stale one fails without saying so.
 */
export const JSON_RULES = [
  { what: 'a bare decision citation', re: BARE },
  { what: 'a lettered decision citation', re: BARE_LETTER },
  { what: "the founding list's oldest spelling", re: BARE_HASH },
  /**
   * `D794`, and a correction to it. Merging this repository's two citation classifiers was decided
   * on the grounds that this one is *strictly* better than the docs-site's `NOTATION` — it resolves
   * `M147e`, `(M3a)`, `decision B` and `E4`, which a pattern-only rule provably cannot. Measured,
   * "strictly" was wrong in one direction: `NOTATION` carried two shapes this list did not, and a
   * merge that simply adopted this one would have quietly stopped checking both. They are correct
   * for the package-metadata corpus too — a `D105` or a `P#75` in a product blurb is exactly what
   * `D714` says to delete — so they are added here rather than kept on one side.
   */
  // `M164-11`: `D\d{1,3}`, not `D\d{2,3}`. The arity arrived with the pattern when `M158c`/`D794`
  // merged this repository's two citation classifiers, and it was never measured against the
  // sequence it classifies: tflw numbers decisions from `D1` and publishes `D1`, `D5`, `D6`, `D7`
  // and `D9`, so at two digits this rule — the only one over shipped npm metadata and the public
  // docs site — could not see five of the identifiers it exists to keep out of them. That is the
  // third copy of `M154d`'s defect, found by sweeping every D-arity in both repositories while
  // repairing `M164-10`, which is the sweep `M154d` itself did not do.
  //
  // Measured before widening (`D716`): zero `\bD\d\b` in every string of every tracked
  // `package.json` in both repositories and on all 41 tracked docs-site pages. Nothing moves
  // today; the value is the next leak.
  { what: 'a decision', re: /\bD\d{1,3}\b/g },
  { what: 'a plan item', re: /\bP#\d+[a-z]?\b/g },
  /**
   * `M147e`, `(M3a)`. Label form carries no record name, so `NAMES_RECORD` provably cannot reach
   * it — it is how the two sites this gate was widened for are written, and it measured **zero**
   * false positives across every string in every tracked `package.json` in both repositories
   * (`D717`).
   */
  { what: 'a milestone label', re: /(?<![\w#])M\d{1,3}[a-z]?\d?\b/g },
  /** A review-ledger row: `M147-10`, `DT-4`, `FU-11`. Same evidence as the labels. */
  { what: 'a review-ledger row', re: /(?<![\w#])(?:[A-Z]{1,3}\d+|DT|FU)-\d+\b/g },
  /**
   * A private design record named outright. Only the filename forms: `NAMES_RECORD`'s bare `PLAN`
   * and bare `enterprise` are dropped here, because in a product blurb they are ordinary English
   * and the citations that carry them are caught by their number anyway.
   */
  { what: 'a record this reader cannot open', re: /\b(?:PLAN[A-Za-z0-9_]*|PROGRESS|REVIEW_[A-Z_]+)\.md\b/g },
];
