#!/usr/bin/env node
// Generates `packages/ui/src/fonts.css` — the `@font-face` declarations for the four themes'
// five families (`M213` `S0`, `D1098`).
//
// WHY GENERATED. Each `@fontsource` package ships a stylesheet naming every subset it was built
// with — cyrillic, cyrillic-ext, greek, vietnamese, latin, latin-ext — and importing it emits every
// one into `dist/ui/assets/`, 1.4 MB for IBM Plex Sans alone, of which a browser downloads none:
// `unicode-range` gates the fetch, so the whole cost lands in the tarball and none of it in the
// page. Picking subsets means writing the faces out by hand, and a hand-written `unicode-range` is
// a number somebody typed that is wrong the first time a subsetter changes. So the blocks are
// LIFTED from each package's own stylesheet verbatim and only the `url()` is rewritten, from the
// package-relative `./files/…` to a bare specifier Vite resolves and fingerprints.
//
// Run after any `@fontsource*` version bump: `node scripts/gen-fonts.mjs`. The output is committed,
// so a bump that changes a face shows up as a diff rather than as a silent change at build time.
//
// IBM PLEX MONO IS NOT VARIABLE. There is no `@fontsource-variable/ibm-plex-mono` — the family has
// no variable release — so it is vendored static at the two weights the themes ask for (400, and
// 600 for `--kw-weight`). `D1098` says "five variable families"; it is four plus one static, and
// the plan is amended at `§3` rather than left reading as if the fifth were something it is not.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const NM = join(ROOT, 'node_modules');
const OUT = join(ROOT, 'packages', 'ui', 'src', 'fonts.css');

/** [package, the stylesheet inside it, the subsets to keep]. A variable family's whole weight axis
 *  is one file per subset (`wght.css`); a static one is a file per subset AND weight. */
const WANT = [
  ['@fontsource-variable/ibm-plex-sans', 'wght.css', ['latin', 'latin-ext']],
  ['@fontsource-variable/jetbrains-mono', 'wght.css', ['latin', 'latin-ext']],
  ['@fontsource-variable/manrope', 'wght.css', ['latin', 'latin-ext']],
  ['@fontsource-variable/public-sans', 'wght.css', ['latin', 'latin-ext']],
  ['@fontsource/ibm-plex-mono', 'latin-400.css', ['latin']],
  ['@fontsource/ibm-plex-mono', 'latin-ext-400.css', ['latin-ext']],
  ['@fontsource/ibm-plex-mono', 'latin-600.css', ['latin']],
  ['@fontsource/ibm-plex-mono', 'latin-ext-600.css', ['latin-ext']],
];

const HEAD = `/* \`M213\` \`S0\` (\`D1098\`) — the five families the four themes are set in, vendored.
 *
 * GENERATED by \`scripts/gen-fonts.mjs\`, not hand-written: every block below was lifted verbatim
 * from the \`@fontsource\` package's own stylesheet, so the \`unicode-range\` on each face is the
 * subsetter's and not a number somebody typed. The only edits are the \`url()\`, rewritten from the
 * package-relative \`./files/…\` to a bare specifier Vite resolves and fingerprints, and the
 * omissions below.
 *
 * WHAT IS OMITTED, AND WHY EACH IS A DECISION RATHER THAN AN OVERSIGHT.
 *   · **Subsets.** \`latin\` and \`latin-ext\` only. Each package ships cyrillic, cyrillic-ext, greek
 *     and vietnamese too; importing the package's own \`wght.css\` would emit every one of them into
 *     \`dist/ui/assets/\` — 1.4 MB for IBM Plex Sans alone — and a browser would still download none
 *     of them, because \`unicode-range\` gates the fetch. The cost is entirely in the shipped
 *     tarball, which is the thing \`D1098\` was sizing. Measured: 12 files, 275 KB, all five families.
 *   · **Italics.** None. \`Terminal\` sets \`--com-style: italic\` and \`.elsewhere\` is italic prose;
 *     both render as the browser's synthetic oblique. The real italic faces cost 119 KB across the
 *     two families that would use them, against two small pieces of text.
 *   · **IBM Plex Mono is NOT variable.** There is no \`@fontsource-variable/ibm-plex-mono\` — the
 *     family has no variable release — so it is vendored static at 400 and 600, the two weights
 *     \`--kw-weight\` asks for. \`D1098\`'s "five variable families" is four plus one static; amended
 *     in the plan at \`§3\`, and recorded here because this is where a reader meets the asymmetry.
 *
 * All five packages are OFL-1.1, verified from each package's own \`LICENSE\` file and never its
 * README, and carried into \`THIRD-PARTY-NOTICES.md\` by the generator that reads the bundle's own
 * metafile — which could not see a font at all until \`M213-11\`.
 */

`;

const blocks = [];
for (const [pkg, file, subsets] of WANT) {
  const css = readFileSync(join(NM, pkg, file), 'utf8');
  for (const m of css.matchAll(/@font-face\s*\{[^}]*\}/g)) {
    const block = m[0];
    const url = /url\(\.\/(files\/[^)]+\.woff2)\)/.exec(block);
    if (!url) continue; // the `woff` fallback blocks: legacy, and nothing this page supports needs them
    const name = url[1];
    if (!subsets.some((s) => new RegExp(`-${s}-(wght|\\d{3})-`).test(name))) continue;
    if (/italic/.test(name)) continue;
    // **The `.woff` fallback is dropped, and it was never a fallback.** The static family's `src`
    // lists woff2 AND woff; rewriting only the woff2 left the woff as a package-relative
    // `./files/…` that Vite could not resolve — it printed *didn't resolve at build time* and
    // shipped a dead URL inside the stylesheet, which is worse than no fallback at all. Nothing
    // that could use it can run this page anyway: woff2 has been universal since 2016 and this
    // build already requires `color-mix`, `:focus-visible` and `all: revert`.
    const woff2Only = block.replace(/,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\('woff'\)/, '');
    blocks.push(woff2Only.replace(/url\(\.\/files\//, `url('${pkg}/files/`).replace(/\.woff2\)/, ".woff2')"));
  }
}

if (blocks.length === 0) throw new Error('gen-fonts: no faces matched — a package layout changed');
writeFileSync(OUT, HEAD + blocks.join('\n\n') + '\n');
console.log(`gen-fonts: ${blocks.length} @font-face blocks -> ${OUT}`);
