import { defineConfig } from 'vitepress';
import tflwGrammar from '../../vscode/syntaxes/tflw.tmLanguage.json' with { type: 'json' };

// Decision 16.3 (PLAN_ENTERPRISE.md): Home · Getting Started · Guide (12 sub-topics, 2 added for
// the browser arc — see PLAN.md decision 112) · Reference · Grammar · Changelog. `appearance` is
// intentionally left unset — VitePress's default (`true`)
// already shows a light/dark toggle that respects the reader's OS preference (decision 16.12);
// overriding it would be the wrong direction.

/** The guide rail, hoisted to a `const` so the two sidebar keys that need it (`/guide/` and
 * `/getting-started`, `M125e`/`FU-30`) name one array instead of holding two copies of it. */
const GUIDE_SIDEBAR = [
  {
    text: 'Getting started',
    items: [{ text: 'Install & quickstart', link: '/getting-started' }],
  },
  {
    text: 'Guide',
    items: [
      { text: '1. Writing your first test', link: '/guide/first-test' },
      { text: '2. Config & environments', link: '/guide/config' },
      { text: '3. Sessions & auth', link: '/guide/sessions' },
      { text: '4. Assertions in depth', link: '/guide/assertions' },
      { text: '5. Variables, generators & expressions', link: '/guide/variables' },
      { text: '6. Actions, imports & the JS escape hatch', link: '/guide/actions' },
      { text: '7. Browser testing: interacting with a UI', link: '/guide/browser-basics' },
      { text: '8. Browser testing: advanced scenarios', link: '/guide/browser-advanced' },
      { text: '9. Data-driven tests & hooks', link: '/guide/data-and-hooks' },
      { text: '10. Retry, polling & flaky handling', link: '/guide/retry-and-polling' },
      { text: '11. CI, reporting & safety', link: '/guide/ci-and-reporting' },
      { text: '12. Running & debugging tests', link: '/guide/debugging' },
      { text: '13. Load testing: scenarios & thresholds', link: '/guide/load-testing' },
      { text: '14. Security hygiene scanning', link: '/guide/security-scanning' },
      { text: '15. Authorization testing', link: '/guide/authorization-testing' },
      { text: '16. Input-handling testing', link: '/guide/input-handling' },
      { text: '17. Findings, baselines & the gate', link: '/guide/findings-and-baselines' },
      { text: '18. Crawling an undocumented surface', link: '/guide/crawling' },
    ],
  },
];

export default defineConfig({
  title: 'tflw',
  description: 'A testing DSL for API and browser tests — reports first, syntax second.',
  // Deployed to https://deepak-tuteja.github.io/tflw/ (a project subpath, not the domain root),
  // so asset/link URLs must be prefixed with /tflw/ or the built CSS/JS 404 on GitHub Pages.
  base: '/tflw/',
  cleanUrls: true,
  lastUpdated: true,
  srcExclude: ['**/README.md'],

  // The brand mark (PLAN_BRAND_MARK.md) — supersedes the placeholder checkmark that
  // PLAN_DOCS_SITE_UPDATE.md decision 6 shipped as a stand-in. Every file below is generated by
  // `npm run brand`, which owns the path data; edit the script, never these outputs.
  //
  // `favicon.svg` carries its own `@media (prefers-color-scheme: dark)` because a browser tab
  // can't see this site's theme toggle — only the OS preference. The PNGs are a raster fallback
  // for the handful of clients that still ignore SVG favicons. Paths are base-prefixed by hand:
  // head tags aren't rewritten for a custom `base` the way markdown links are.
  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/tflw/favicon.svg' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/tflw/favicon-32.png' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/tflw/favicon-16.png' }],
    ['link', { rel: 'apple-touch-icon', href: '/tflw/apple-touch-icon.png' }],
  ],

  // Real syntax highlighting for ```tflw / ```tflw-config fences (M22, root test-coverage audit
  // follow-up) — reuses the same TextMate grammar the VS Code extension ships, so a code sample
  // colors identically to the editor rather than falling back to shiki's plain-text default for
  // an unregistered language.
  markdown: {
    languages: [{ ...(tflwGrammar as object), aliases: ['tflw-config'] }],
  },

  themeConfig: {
    // Two files rather than one self-switching SVG: VitePress's dark mode is a manual class flip
    // on <html>, which a `prefers-color-scheme` query inside the file can't see. `siteTitle: false`
    // drops the text "tflw" beside it — the wordmark already spells the name, and rendering both
    // says it twice. `title` above still drives the document <title>.
    //
    // NOT base-prefixed, unlike the `head` links above — themeConfig paths *are* rewritten for
    // `base`, so writing `/tflw/logo-light.svg` here yields `/tflw/tflw/logo-light.svg` and 404s.
    logo: { light: '/logo-light.svg', dark: '/logo-dark.svg' },
    siteTitle: false,

    nav: [
      { text: 'Guide', link: '/guide/first-test' },
      { text: 'Reference', link: '/reference/matchers' },
      { text: 'Grammar', link: '/grammar' },
      { text: 'Editor', link: '/editor' },
      { text: 'Playground', link: '/playground' },
      { text: "What's new", link: '/whats-new' },
      { text: 'Changelog', link: '/changelog' },
    ],

    sidebar: {
      // `M125e`/`FU-30`/D282. `getting-started.md` lives at `/getting-started`, not under
      // `/guide/`, so before this it matched no key but the `/` fallback and the page the home
      // page's primary CTA points at rendered the *More* rail — Grammar, Playground, Changelog —
      // instead of the thirteen-step guide it is the entrance to.
      //
      // Two keys naming ONE array, not two copies. VitePress resolves the longest matching path
      // prefix, so `/getting-started` beats `/` with no effect on any other page. Moving the file
      // under `guide/` was the other repair and was rejected: it changes a published URL that the
      // home CTA, the README and the npm page all point at, to fix a left rail.
      '/guide/': GUIDE_SIDEBAR,
      '/getting-started': GUIDE_SIDEBAR,
      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Matchers', link: '/reference/matchers' },
            { text: 'Generators', link: '/reference/generators' },
            { text: 'CLI flags', link: '/reference/cli' },
            { text: 'Diagnostic codes', link: '/reference/diagnostics' },
          ],
        },
      ],
      // Fallback for every standalone page with no more-specific key above (grammar.md,
      // editor.md, playground/index.md, whats-new.md, changelog.md) — without this, those pages
      // render with no left sidebar at all (`hasSidebar` false), which reads as inconsistent
      // chrome next to guide/reference's sidebar + "On this page" two-column layout. VitePress
      // resolves the longest matching path prefix, so this never overrides the more specific keys
      // above.
      '/': [
        {
          text: 'More',
          items: [
            { text: 'Grammar', link: '/grammar' },
            { text: 'Editor support', link: '/editor' },
            { text: 'Playground', link: '/playground' },
            { text: "What's new", link: '/whats-new' },
            { text: 'Changelog', link: '/changelog' },
          ],
        },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/deepak-tuteja/tflw' }],

    search: { provider: 'local' },
  },
});
