#!/usr/bin/env node
// Generates `src/docs-data.generated.ts`, what `tflw docs [topic]` prints, from the docs site's own
// Guide and Reference pages (`packages/docs-site/src/content/docs/guide/*.md`, `reference/*.md`),
// grouped and ordered as the site's sidebar groups them (`packages/docs-site/src/sidebar.mjs`, which
// this imports — the site and the terminal read one list). Not committed (see root .gitignore):
// regenerated by `pretest`/`predev`/`bundle` so it can never drift from the pages.
//
// `M263`: this read SPEC.md until then, and SPEC is a design record: of 71 topics, 63 cited `§`
// numbers, 43 named milestones, 40 carried decision ids, and `tflw docs unique` explained a repair
// and the dogfood suite's degraded tests. The pages are written for a user, linked from the
// walkthrough, and already held to the product by the site's own gates, so they are the one source
// of user prose and the terminal prints them.
//
// The pages are markdown for the docs site, so this is a small renderer, and a *closed* one: it knows
// the constructs the pages use (`:::tip`/`:::caution` asides, fences, `{#id}` anchors, links, the
// reference pages' generated tables) and throws on anything else, so a page that grows a new
// construct fails the build instead of reaching a terminal half-rendered. The tables are not copied:
// a table becomes a description of rows (which manifest, which filter, which columns), and
// `src/docs-topics.ts` renders it from the same `spec-data.ts` manifests the site renders from.
//
// `M269`: the site renders those tables with `parseTable` and `parseScript` below too
// (`packages/docs-site/src/lib/markdown.mjs`), so a table the terminal can read and a table the site
// can draw are one grammar, not two that agree today.
//
// Everything below `main()` is a pure function of strings, exported for `test/gen-docs.test.ts`.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import * as SIDEBAR from '../../docs-site/src/sidebar.mjs';

/** Where a link to a site page that `tflw docs` does not print is sent instead. */
export const SITE = 'https://deepak-tuteja.github.io/tflw';

/** The manifests a reference table may draw rows from — `@tflw/lang`'s re-export of `spec-data.ts`. */
export const MANIFESTS = ['CLI_FLAGS', 'DIAGNOSTICS', 'GENERATORS', 'MATCHERS'];

// Starlight's aside names (`M269`); `caution` keeps the terminal's word for it from VitePress days.
const CONTAINERS = { tip: 'Tip', caution: 'Warning' };

export function slugify(title) {
  return title
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

/**
 * The site's Guide and Reference sidebars, in order: `[{ group, pages: [{ slug, dir, text, overview }] }]`.
 * Read off the site's own navigation data (`packages/docs-site/src/sidebar.mjs`): a group's `link` is
 * its overview page and each item is a page. Only `/guide/` and `/reference/` links are kept;
 * `getting-started` is the walkthrough's to teach.
 */
export function parseSidebar({ GUIDE_SIDEBAR, SIDEBARS }) {
  if (!Array.isArray(GUIDE_SIDEBAR) || !Array.isArray(SIDEBARS?.['/reference/'])) {
    throw new Error('gen-docs: sidebar.mjs has no GUIDE_SIDEBAR or /reference/ sidebar');
  }
  const groups = [];
  for (const g of [...GUIDE_SIDEBAR, ...SIDEBARS['/reference/']]) {
    const group = { group: g.text, pages: [] };
    const page = (link, text, overview) => {
      const m = /^\/(guide|reference)\/([a-z0-9-]+)$/.exec(link);
      if (m) group.pages.push({ slug: m[2], dir: m[1], text, overview });
    };
    if (g.link) page(g.link, g.text, true);
    for (const item of g.items ?? []) page(item.link, item.text, false);
    groups.push(group);
  }
  return groups.filter((g) => g.pages.length > 0);
}

/** `<td …>` cell → its column: `code(x.key)`, `{{ x.key }}`, `<code>{{ x.key }}</code>`, or the one
 * status ternary. Anything else throws. `form` says which, for the site's renderer: the terminal
 * prints all three the same way, and the page does not. */
function parseCell(td, row) {
  const html = new RegExp(`^<td v-html="code\\(${row}\\.(\\w+)\\)"\\s*/>$`).exec(td);
  if (html) return { key: html[1], form: 'markdown' };
  const text = new RegExp(`^<td>(<code>)?\\{\\{\\s*${row}\\.(\\w+)\\s*\\}\\}(?:</code>)?</td>$`).exec(td);
  if (text) return { key: text[2], form: text[1] ? 'code' : 'text' };
  const status = new RegExp(`^<td>\\{\\{\\s*${row}\\.(\\w+) === '(\\w+)' \\? '([^']*)' : '([^']*)'\\s*\\}\\}</td>$`).exec(td);
  if (status) return { key: status[1], form: 'status', when: status[2], yes: status[3], no: status[4] };
  throw new Error(`gen-docs: a table cell tflw docs cannot render: ${td}`);
}

/** A reference page's `<table>` → `{ table: { source, where?, cols } }`, resolved against the page's
 * `<script setup>` constants (`const runFlags = CLI_FLAGS.filter((f) => f.command === 'run')`). */
export function parseTable(html, consts) {
  const labels = [...html.matchAll(/<th>([^<]*)<\/th>/g)].map((m) => m[1]);
  const loop = /<tr v-for="(\w+) in (\w+)"/.exec(html);
  if (!loop) throw new Error(`gen-docs: a table with no v-for row: ${html.slice(0, 80)}`);
  const [, row, name] = loop;
  const resolved = MANIFESTS.includes(name) ? { source: name } : consts[name];
  if (!resolved) throw new Error(`gen-docs: a table iterates \`${name}\`, which is neither a manifest nor a filter the page declares`);
  const body = html.slice(loop.index);
  const cells = [...body.matchAll(/<td[^>]*?(?:\/>|>.*?<\/td>)/g)].map((m) => parseCell(m[0], row));
  if (cells.length !== labels.length) throw new Error(`gen-docs: a table with ${labels.length} headings and ${cells.length} cells`);
  return { table: { ...resolved, cols: cells.map((c, i) => ({ label: labels[i], ...c })) } };
}

/** The `<script setup>` filters a reference page declares: `{ runFlags: { source: 'CLI_FLAGS', where: { key: 'command', value: 'run' } } }`. */
export function parseScript(script) {
  const consts = {};
  for (const m of script.matchAll(/const (\w+) = (\w+)\.filter\(\((\w+)\) => \3\.(\w+) === '([^']+)'\);/g)) {
    if (!MANIFESTS.includes(m[2])) throw new Error(`gen-docs: \`${m[1]}\` filters \`${m[2]}\`, which is not a manifest`);
    consts[m[1]] = { source: m[2], where: { key: m[4], value: m[5] } };
  }
  return consts;
}

/** `[text](href)` → what a terminal can follow: another topic as `tflw docs <slug>`, any other site
 * page as its URL, an outside link as itself, a same-page anchor as the text alone. */
export function renderLinks(line, topics) {
  return line.replace(/\[((?:[^[\]]|\[[^\]]*\])+)\]\(([^()\s]+)\)/g, (_, text, href) => {
    if (href.startsWith('#')) return text;
    if (/^https?:/.test(href)) return text === href ? href : `${text} (${href})`;
    const path = href.replace(/^\.\//, '/guide/').replace(/^\.\.\//, '/').replace(/\.(md|html)(?=#|$)/, '');
    const page = /^\/(?:guide|reference)\/([a-z0-9-]+)(?:#.*)?$/.exec(path) ?? /^([a-z0-9-]+)(?:#.*)?$/.exec(path);
    if (page && topics.has(page[1])) return `${text} (tflw docs ${page[1]})`;
    return `${text} (${SITE}${path.startsWith('/') ? '' : '/'}${path})`;
  });
}

/**
 * One page → `{ title, intro, sections: [{ slug, title, body }] }`, each body a list of segments
 * (strings, and table descriptions). Closed over the constructs listed in the header comment.
 */
export function renderPage(md, topics, name = 'page') {
  const lines = md.split('\n');
  let i = 0;
  if (lines[0] === '---') {
    i = lines.indexOf('---', 1) + 1;
    if (i === 0) throw new Error(`gen-docs: ${name}: unclosed frontmatter`);
  }
  let consts = {};
  let title = '';
  const intro = [];
  const sections = [];
  let out = intro;
  // Lines wait here until a heading, a table or the end flushes them, each marked prose or code:
  // links are rendered over a run of prose lines at once, because a link's text wraps across a
  // line break as often as not (`[Performance⏎testing](/guide/performance)`).
  let text = [];
  const flush = () => {
    const lines = [];
    for (let k = 0; k < text.length; ) {
      if (!text[k].prose) lines.push(text[k++].line);
      else {
        let j = k;
        while (j < text.length && text[j].prose) j++;
        lines.push(...renderLinks(text.slice(k, j).map((t) => t.line).join('\n'), topics).split('\n'));
        k = j;
      }
    }
    if (lines.length > 0) out.push(lines.join('\n'));
    text = [];
  };
  const prefix = []; // one entry per open `:::` container
  const emit = (line, prose = true) => text.push({ line: line === '' ? '' : prefix.join('') + line, prose });

  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === '<script setup>') {
      const end = lines.indexOf('</script>', i);
      if (end === -1) throw new Error(`gen-docs: ${name}: unclosed <script setup>`);
      consts = { ...consts, ...parseScript(lines.slice(i + 1, end).join('\n')) };
      i = end + 1;
      continue;
    }
    const fence = /^(\s*)(`{3,}|~{3,})/.exec(line);
    if (fence) {
      const close = new RegExp(`^\\s*${fence[2][0]}{${fence[2].length},}\\s*$`);
      let j = i + 1;
      while (j < lines.length && !close.test(lines[j])) j++;
      if (j === lines.length) throw new Error(`gen-docs: ${name}:${i + 1}: unclosed code fence`);
      for (const code of lines.slice(i + 1, j)) emit(code.trim() === '' ? '' : `    ${code.slice(Math.min(fence[1].length, code.search(/\S/)))}`, false);
      i = j + 1;
      continue;
    }
    if (line.trim() === '<table>') {
      const end = lines.indexOf('</table>', i);
      if (end === -1) throw new Error(`gen-docs: ${name}:${i + 1}: unclosed <table>`);
      flush();
      out.push(parseTable(lines.slice(i, end + 1).join('\n'), consts));
      i = end + 1;
      continue;
    }
    const container = /^:::(?:(\w+)(?:\[(.*)\])?)?$/.exec(line.trim());
    if (container) {
      if (container[1] === undefined) {
        if (prefix.length === 0) throw new Error(`gen-docs: ${name}:${i + 1}: a ::: closes nothing`);
        prefix.pop();
      } else {
        const label = CONTAINERS[container[1]];
        if (!label) throw new Error(`gen-docs: ${name}:${i + 1}: a :::${container[1]} aside tflw docs cannot render`);
        emit(`${label}${container[2] ? `: ${container[2]}` : ':'}`);
        prefix.push('  ');
      }
      i++;
      continue;
    }
    const heading = /^(#{1,6})\s+(.*?)(?:\s+\{#[\w-]+\})?\s*$/.exec(line);
    if (heading && prefix.length === 0) {
      const level = heading[1].length;
      const words = renderLinks(heading[2], topics);
      if (level === 1) {
        if (title === '') title = words;
      } else if (level === 2) {
        flush();
        out = [];
        sections.push({ slug: slugify(heading[2]), title: words, body: out });
      } else {
        emit(`▸ ${words}`);
      }
      i++;
      continue;
    }
    if (/!\[/.test(line)) throw new Error(`gen-docs: ${name}:${i + 1}: a picture, which a terminal cannot show`);
    if (/<[A-Z][A-Za-z]*[\s>/]/.test(line.replace(/`[^`]*`/g, ''))) throw new Error(`gen-docs: ${name}:${i + 1}: a Vue component tflw docs cannot render: ${line.trim()}`);
    emit(line);
    i++;
  }
  if (prefix.length > 0) throw new Error(`gen-docs: ${name}: an unclosed ::: container`);
  flush();
  if (title === '') throw new Error(`gen-docs: ${name}: no # title`);
  const trim = (segs) => {
    const out = segs.map((s) => (typeof s === 'string' ? s.replace(/^\n+|\n+$/g, '') : s)).filter((s) => s !== '');
    return out;
  };
  return { title, intro: trim(intro), sections: sections.map((s) => ({ ...s, body: trim(s.body) })) };
}

/** The whole topic table: one per sidebar page, in sidebar order, each with its group. Throws when a
 * page on disk is in no sidebar or a sidebar page has no file — the two would otherwise disagree. */
export function buildPages(docsRoot, sidebar) {
  const groups = parseSidebar(sidebar);
  const listed = groups.flatMap((g) => g.pages);
  const topics = new Set(listed.map((p) => p.slug));
  for (const dir of ['guide', 'reference']) {
    for (const f of readdirSync(join(docsRoot, dir)).filter((f) => f.endsWith('.md'))) {
      if (!listed.some((p) => p.dir === dir && `${p.slug}.md` === f)) throw new Error(`gen-docs: ${dir}/${f} is in no sidebar, so tflw docs would not list it`);
    }
  }
  const pages = [];
  for (const g of groups) {
    for (const p of g.pages) {
      const name = `${p.dir}/${p.slug}.md`;
      const page = renderPage(readFileSync(join(docsRoot, name), 'utf8'), topics, name);
      pages.push({ slug: p.slug, title: page.title, listTitle: p.overview ? g.group : p.text, group: g.group, intro: page.intro, sections: page.sections });
    }
  }
  return pages;
}

function main() {
  const docsRoot = fileURLToPath(new URL('../../docs-site/src/content/docs/', import.meta.url));
  const outPath = fileURLToPath(new URL('../src/docs-data.generated.ts', import.meta.url));
  const pages = buildPages(docsRoot, SIDEBAR);
  // The header keeps its pre-`M269` path on purpose: this file sits in `src/`, which is a hashed
  // input of the docs site's screenshots (`packages/ui/scripts/screenshot-inputs.mjs`), so a change
  // to these bytes is a re-cut of every picture for no visible difference.
  const out = `// AUTO-GENERATED by scripts/gen-docs.mjs from packages/docs-site/{guide,reference}/*.md — do not edit
// by hand. Regenerated by \`npm run docs:gen\` (also runs before dev/test/bundle) so it can never drift
// from the pages that produced it. \`src/docs-topics.ts\` renders it.
import type { DocsPageSource } from './docs-topics.js';

export const DOCS_PAGES: readonly DocsPageSource[] = ${JSON.stringify(pages, (k, v) => (k === 'form' ? undefined : v), 2)};
`;
  writeFileSync(outPath, out, 'utf8');
  console.log(`gen-docs: wrote ${pages.length} topics (${pages.reduce((n, p) => n + p.sections.length, 0)} sections) to ${outPath}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
