#!/usr/bin/env node
// Generates `src/docs-data.generated.ts` from the monorepo's SPEC.md — the single source of
// truth for matchers/generators/grammar. `tflw docs [topic]` reads this generated module at
// runtime; SPEC.md itself isn't shipped in the npm package, so a live parse at runtime isn't an
// option. Regenerated by `pretest`/`predev`/`bundle` (decision 93) so it can never drift from the
// SPEC.md that produced it — not source-committed (see root .gitignore).
//
// `parseSpecToTopics` is exported (pure, no I/O) so a test can exercise the parsing logic against
// a small fixture string instead of the real ~800-line SPEC.md, keeping the test fast and stable
// against future SPEC.md edits. The file's own top-level code only runs the read/write side when
// invoked directly (`node scripts/gen-docs.mjs`), not when imported.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// A handful of headings whose literal-text auto-slug wouldn't be what a user actually types —
// everything else derives its topic name straight from the heading (backticked single keywords,
// e.g. `retry`/`capture`/`let`, already slug cleanly with no help needed).
export const ALIASES = {
  'the-config-dialect': 'config',
  'partial-object-matching': 'subset',
  'array-quantifiers': 'quantifiers',
  'matcher-table': 'matchers',
  'events-report-ci-outputs': 'events',
};

export function slugify(title) {
  return title
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

function headingTitle(raw) {
  let title = raw;
  title = title.replace(/\s*(✅|🔧|🔮)\s*$/u, ''); // trailing status marker
  title = title.replace(/\s*\([^)]*\)\s*$/, '').trim(); // trailing "(P#..)"/"(TFLW-GAPS.md ...)"
  title = title.replace(/^\d+(\.\d+)*\.?\s*/, ''); // leading "N." / "N.M" numbering
  return title;
}

/** Parses `##`/`###` headings + their body text (up to the next heading of either level) into a
 * topic-slug-keyed map. Pure function of `text` + an alias table — no file I/O. */
export function parseSpecToTopics(text, aliases = ALIASES) {
  const lines = text.split('\n');
  const sections = [];
  let current = null;
  for (const line of lines) {
    const m = /^(##|###)\s+(.*)$/.exec(line);
    if (m) {
      if (current) sections.push(current);
      const title = headingTitle(m[2]);
      const slugSource = title.split('—')[0].trim();
      const slug = aliases[slugify(slugSource)] ?? slugify(slugSource);
      current = { slug, title, body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) sections.push(current);

  /** @type {Record<string, { title: string; body: string }>} */
  const topics = {};
  for (const s of sections) {
    const body = s.body.join('\n').replace(/^\n+|\n+$/g, '');
    if (!body) continue; // a heading with no body text of its own (only child subsections)
    if (topics[s.slug]) throw new Error(`duplicate docs topic slug "${s.slug}" — add/adjust an ALIASES entry in gen-docs.mjs`);
    topics[s.slug] = { title: s.title, body };
  }
  return topics;
}

function main() {
  const specPath = fileURLToPath(new URL('../../../SPEC.md', import.meta.url));
  const outPath = fileURLToPath(new URL('../src/docs-data.generated.ts', import.meta.url));
  const specText = readFileSync(specPath, 'utf8');
  const topics = parseSpecToTopics(specText);
  const out = `// AUTO-GENERATED by scripts/gen-docs.mjs from SPEC.md — do not edit by hand.
// Regenerated by \`npm run docs:gen\` (also runs before dev/test/bundle) so this can never drift
// from the SPEC.md that produced it.
export const DOCS_TOPICS: Readonly<Record<string, { readonly title: string; readonly body: string }>> = ${JSON.stringify(topics, null, 2)};
`;
  writeFileSync(outPath, out, 'utf8');
  console.log(`gen-docs: wrote ${Object.keys(topics).length} topics to ${outPath}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
